image: python:2.7.12

flask-test:
  before_script:
    - "cd /builds/Sood/vgstation-statistics"
    - "pip install -r requirements.txt"
  script:
    - "python run.py ci"
  after_script:
    - bash <(curl -s https://codecov.io/bash)
