image: python:2.7.12

flask-test:
  before_script:
    - "cd $CI_PROJECT_DIR"
    - "pip install -r requirements.txt"
  script:
    - "coverage run runtests.py"
  after_script:
    - bash <(curl -s https://codecov.io/bash)
